# Generated by Django 4.2.3 on 2023-08-11 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagen',
            new_name='Imagenes',
        ),
    ]
