# Generated by Django 4.2.3 on 2023-08-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesar', '0002_rename_imagen_imagenes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagenes',
            new_name='Picture',
        ),
    ]
