# Generated by Django 4.2.3 on 2023-08-11 21:03

from django.db import migrations, models
import procesar.models


class Migration(migrations.Migration):

    dependencies = [
        ('procesar', '0003_rename_imagenes_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='nombre_archivo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=procesar.models.generate_filename),
        ),
    ]
